### ISSUE TITLE
Equivalent Nodes In Dataset

### ISSUE THREAD

**Issue by kl2806** [stanfordnlp/web-elements#10]
I'm wondering how the list of `equiv` nodes are generated in the dataset. From my understanding of the paper, crowdworkers reference exactly one element, but there is a list of xids in the dataset. Were there additional manual annotations in a later step to find equivalent nodes to `xid`, or were the equivalent nodes programmatically generated? 

Below is an example from `combined-v2-cleaned.train.jsonl`. Thanks!

`{"equiv": [133, 135, 139], "exampleId": "32N49TQG3HCKR3W5C65VPBKPDP4AV2_a1", "phrase": "click first article", "
version": "v6", "webpage": "247wallst.com", "xid": 133}`

**Comment by ppasupat** [comment]
Sorry for the late reply. We detected links (`<a>`) with the same `href` and put them in this "equiv" field. I don't think we actually use it since some queries treat such equivalent links as different (e.g., "click the about link on the top menu"). We had an idea of using it as a partial reward but we didn't get to that either.

**Comment by kl2806** [comment]
thanks! that makes sense.
